[package]
name = "bkhdflatcomp02"
version = "0.1.0"
authors = ["jpretired"]
edition = "2024"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "^0"
qndr = "^0"
